### ISSUE TITLE
使用更加透明的文件格式

### ISSUE THREAD

**Issue by FiveYellowMice** [nadebula/stupid_patent#1]
ODT 虽然是个自由的文件格式，但它还是二进制文件，这样在 GitHub 上难以预览，也不容易被 Git 跟踪修改。这些缺点会导致许多文迪，比如，如果在移动设备上想要阅读文章就比较麻烦；进行 PR 时也难以追踪修改；文件多了以后用 Git 也会比较卡。

我认为更好的方式是使用一个标记语言，这样就可以避免上述的缺陷以及它们导致的问题了。

**Comment by tonghuix** [comment]
而且貌似这些文档也很简单，只需要markdown的基础语法就够了。

推荐可以用 Pandoc 可以直接将 odt 文件转换成 markdown

**Comment by nadebula** [comment]
已更新 markdown 并移除二进制文件，方便各位查看及校正。
